### ISSUE TITLE
JSON pretty printer modifies message content

### ISSUE THREAD

**Issue by winne42** [kumait/kafkavisualizer#1]
We observed that "Format JSON" modifies the content of messages read from Kafka by escaping certain characters:

![image](https://user-images.githubusercontent.com/21171796/189351113-eff56dfd-bbce-417d-aff7-8b73c474e246.png)

We tracked this down as being the default behavior of Gson, for added security if JSON is used in an HTML context. As the messages in kafkavisualizer are not (automatically) in an HTML context, this behavior is unexpected, and in our case unwanted. I will open a PR to disable HTML escaping for JSON pretty-printing.

**Comment by kumait** [comment]
Thanks @winne42, I agree, I will merge your PR.
