### ISSUE TITLE
Add formatting for XML code

### ISSUE THREAD

**Issue by tbrv** [kumait/kafkavisualizer#3]
XML is still a popular format and lots of people write XML-encoded data to Kafka. Unformatted XML is almost unlegible and it would be nice if Kafka Visualizer would support this. 

Proposal: add an aditional checkbox for XML formatting. Selecting this checkbox unselects the format JSON checkbox. 

Alternatives
- Radio buttons: (o) None ( ) JSON ( ) XML
- Dropdown menu

**Comment by kumait** [comment]
XML format is now implemented in the latest version.
